require 'rails_helper'
require 'capybara/rspec'

RSpec.describe 'Users' do
  before(:each) { get '/users' }


  describe 'Users pages visited', type: :feature do
    it 'Main user page is visited' do
      visit '/users'
      expect(page).to have_text('This is the main page')
    end

    it 'User page by ID is visited' do
      visit '/users/:2?'
      expect(page).to have_text('This page will be dynamically generated by ID')
    end
  end

  describe 'get users#show', type: :request do
    before(:each) { get '/users/:2?' }
    it "renders 'show' in user controller" do
      expect(response).to render_template('show')
    end

    it 'is a success' do
      expect(response).to have_http_status(:ok)
    end
  end

  describe 'get users#index', type: :request do
    before(:each) { get '/users' }
    it "renders 'index' in user controller" do
      expect(response).to render_template('index')
    end

    it 'is a success' do
      expect(response).to have_http_status(:ok)
    end
  end

end 